### ISSUE TITLE
Get permissions very clearly working

### ISSUE THREAD

**Issue by cg505** [frc461/website-2013#13]
This includes a non-confusing explanation about how every part of them works.

**Comment by cg505** [comment]
This needs to be done. Let's set the deadline for Wednesday.

**Comment by braddoeswebdev** [comment]
That sounds like it could happen.

**Comment by rye** [comment]
Looking at the code, we should just scrap this completely and rewrite it such that we have a better understanding of what the code does. Or we should analyze the code, and figure out what it's doing, because it doesn't seem to be doing anything bad, but it's not working, which is a problem.

**Comment by braddoeswebdev** [comment]
I wouldn't have a problem with either of those options.

**Comment by rye** [comment]
I would say, then, that scrapping the code completely would work.

**Comment by braddoeswebdev** [comment]
You might also want to consider handling access control with a simpler system - get rid of permissions entirely and just do things based on fields in the user & groups.

**Comment by rye** [comment]
This needs to be prioritized, and needs to be done very soon.

**Comment by rye** [comment]
Based on the amount of work I've seen done on this, I would recommend that the OI deploy date be pushed back.

Edit:
Or, work on any and all things related to this should be pushed, as often as possible, to another branch, if necessary,
@computerguy505.

**Comment by cg505** [comment]
OI does not need permissions to be working.

**Comment by rye** [comment]
Yes, but this needs to be done as quickly as possible.

**Comment by cg505** [comment]
Yay done.
a24c2e3d30e217b1b32e0b138942027541462f40
