### ISSUE TITLE
Todo list? (lower priority)

### ISSUE THREAD

**Issue by cg505** [frc461/website-2013#15]
Add a todo list interface.

**Comment by samontea** [comment]
I have started working with it (this is my first time doing anything this complicated so it might take a while). It is in the branch TodoTesting I think. Check that out (git it?) Okay I'll stop doing puns. The first one was okay, but the second one was too much. Anyway seriously `git checkout TodoTesting` !

**Comment by samontea** [comment]
Everything is pretty and working! Special formatting was applied for a better mobile experience. Kris is just getting the Ajax stuff worked out, and then all we have left to do is add in the groups stuff when we have groups which may be messy, and then we are done.

**Comment by cg505** [comment]
What happens for todo/show?
