### ISSUE TITLE
Doom? (lowest priority)

### ISSUE THREAD

**Issue by cg505** [frc461/website-2013#16]
Make it so the konami code shows some port of doom.
Maybe try [this](http://www.gizmag.com/play-doom-in-your-web-browser/18787/)?

**Comment by braddoeswebdev** [comment]
Aw, it got pulled because Doom is still under copyright.  Sad.

**Comment by rye** [comment]
Not freedoom. And doom is a bit violent to be putting on a robotics
website...

**Comment by cg505** [comment]
I think you can still get the code, just not the docs.

**Comment by cg505** [comment]
Never mind. That's not right.
