### ISSUE TITLE
Search bar?

### ISSUE THREAD

**Issue by cg505** [frc461/website-2013#17]
Upper-right hand corner, navbar?

**Comment by rye** [comment]
As of c91821e, you can probably just put it under the logo in the sidebar.

**Comment by samontea** [comment]
Yeah upper right in nav. I will add this, but someone else will have to make it work.

**Comment by cg505** [comment]
Not done.

While the search bar is existant, it is not operational.

**Comment by rye** [comment]
Also, it needs to have a variable width (so that it fits in the sidebar)

**Comment by rye** [comment]
It still isn't variable-width.

**Comment by samontea** [comment]
It should be. There is a span 9 class on it. I think you are the only person with that bug.

**Comment by samontea** [comment]
If there is a span 9 then it should vary in width. If you want you can try to make it 12, but I remember that as not working very well.

**Comment by samontea** [comment]
Double checked. You are incorrect. It does vary width. You are wrong. Have you not pulled recently?

**Comment by samontea** [comment]
My git status is clean. Whatever your problem is it isn't my fault. Pull and double check that it isn't just that because it works over here. Also I double checked span12 doesn't work so we are sticking with span9.

**Comment by braddoeswebdev** [comment]
@samercier - chill out, dude.  It's not exactly variable width for me either.  It does shrink, but I think there's a max-width set.

**Comment by samontea** [comment]
There is here too, but that is kind of how it works. Anyway it is as resizable as it can be.

**Comment by rye** [comment]
Then its containing div needs to be resized, because it looks really ugly.

**Comment by cg505** [comment]
Creating a new issue for it.
