### ISSUE TITLE
Authentication: Prevent every-day user from creating a user

### ISSUE THREAD

**Issue by rye** [frc461/website-2013#2]
Make the database such that you can only create a user if you are logged in as an administrator, and such that you have to, for example, run a system of commands in `rails console` to create the administrator's user. From there, the administrator could add the users, or that all could be scripted.

**Comment by cg505** [comment]
Honestly, we should just expand this issue to cover making sure r/w/d/e permissions are enforced on all pages.

**Comment by rye** [comment]
Fixed.
