### ISSUE TITLE
FIRST Branding

### ISSUE THREAD

**Issue by braddoeswebdev** [frc461/website-2013#20]
The FIRST logo & the team number need to be on the site somewhere...

**Comment by cg505** [comment]
Should this be within site content? (Aka stuff in the db)

**Comment by braddoeswebdev** [comment]
I think we at least need to have something to indicate that we're a FIRST team somewhere in the layout.  Other than that, a few things on the home page would probably be sufficient.

**Comment by rye** [comment]
We probably need the FIRST logo in the navbar, and we could just put 461<hr
/> at the top of the sidebar.

**Comment by braddoeswebdev** [comment]
Sounds reasonable.

**Comment by cg505** [comment]
Pretty much done.
