### ISSUE TITLE
Sidebar problems

### ISSUE THREAD

**Issue by cg505** [frc461/website-2013#25]
The sidebar doesn't really work well at about 900px width, but that is still considered tablet.

**Comment by samontea** [comment]
Just add a media query for that case and have it not be displayed then. (Do that in CSS)

**Comment by cg505** [comment]
So from 900px to 767px, you just don't get the sidebar?

**Comment by samontea** [comment]
If it looks better yes.

**Comment by braddoeswebdev** [comment]
That seems ... problematic.  Can you just have it display at the bottom like the phone layout?

**Comment by cg505** [comment]
I am unsure how to do that exactly. That seems like it would be the best solution. We may need to just find and replace every 767px (current phone width) and replace it with something higher (850px or so). That would be similar to what we did with the colors.

**Comment by braddoeswebdev** [comment]
That would also work.

**Comment by rye** [comment]
I'm assuming this is working, with my current viewing. Closing, and marking instead of as a bug, as a feature.
