### ISSUE TITLE
Remove Navbar?

### ISSUE THREAD

**Issue by rye** [frc461/website-2013#27]
It displays the same information as the sidebar. If we could use the sidebar space more efficiently, it might be prettier. Either that, or just make the navbar MUCH thinner (I'm thinking REALLY thin)

**Comment by cg505** [comment]
Maybe. Not completely, but thinner maybe.

**Comment by cg505** [comment]
Changing this to Deploy, not needed for Into Beta

**Comment by rye** [comment]
Needs to be pretty though, ASAP.
