### ISSUE TITLE
rake db:migrate yields a SQLException on a fresh clone

### ISSUE THREAD

**Issue by rye** [frc461/website-2013#31]
<pre>
-- drop_table(:permissions)
rake aborted!
An error has occurred, this and all later migrations canceled:

SQLite3::SQLException: no such table: permissions: DROP TABLE "permissions"
/home/four04/.rvm/gems/ruby-1.9.3-p362/gems/sqlite3-1.3.6/lib/sqlite3/database.rb:91:in `initialize'
/home/four04/.rvm/gems/ruby-1.9.3-p362/gems/sqlite3-1.3.6/lib/sqlite3/database.rb:91:in `new'
/home/four04/.rvm/gems/ruby-1.9.3-p362/gems/sqlite3-1.3.6/lib/sqlite3/database.rb:91:in `prepare'
/home/four04/.rvm/gems/ruby-1.9.3-p362/gems/sqlite3-1.3.6/lib/sqlite3/database.rb:134:in `execute'
/home/four04/.rvm/gems/ruby-1.9.3-p362/gems/activerecord-3.2.9/lib/active_record/connection_adapters/sqlite_adapter.rb:278:in `block in execute'
/home/four04/.rvm/gems/ruby-1.9.3-p362/gems/activerecord-3.2.9/lib/active_record/connection_adapters/abstract_adapter.rb:280:in `block in log'
/home/four04/.rvm/gems/ruby-1.9.3-p362/gems/activesupport-3.2.9/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/four04/.rvm/gems/ruby-1.9.3-p362/gems/activerecord-3.2.9/lib/active_record/connection_adapters/abstract_adapter.rb:275:in `log'
/home/four04/.rvm/gems/ruby-1.9.3-p362/gems/activerecord-3.2.9/lib/active_record/connection_adapters/sqlite_adapter.rb:278:in `execute'
/home/four04/.rvm/gems/ruby-1.9.3-p362/gems/activerecord-3.2.9/lib/active_record/connection_adapters/abstract/schema_statements.rb:256:in `drop_table'
/home/four04/.rvm/gems/ruby-1.9.3-p362/gems/activerecord-3.2.9/lib/active_record/migration.rb:466:in `block in method_missing'
/home/four04/.rvm/gems/ruby-1.9.3-p362/gems/activerecord-3.2.9/lib/active_record/migration.rb:438:in `block in say_with_time'
/home/four04/.rvm/gems/ruby-1.9.3-p362/gems/activerecord-3.2.9/lib/active_record/migration.rb:438:in `say_with_time'
/home/four04/.rvm/gems/ruby-1.9.3-p362/gems/activerecord-3.2.9/lib/active_record/migration.rb:458:in `method_missing'
/home/four04/.rvm/gems/ruby-1.9.3-p362/gems/activerecord-3.2.9/lib/active_record/migration.rb:334:in `method_missing'
/home/four04/Documents/Programming/GitHub/team461WBI/website/db/migrate/20130202205547_destroy_permissions.rb:2:in `<class:DestroyPermissions>'
/home/four04/Documents/Programming/GitHub/team461WBI/website/db/migrate/20130202205547_destroy_permissions.rb:1:in `<top (required)>'
/home/four04/.rvm/gems/ruby-1.9.3-p362/gems/activesupport-3.2.9/lib/active_support/dependencies.rb:251:in `require'
/home/four04/.rvm/gems/ruby-1.9.3-p362/gems/activesupport-3.2.9/lib/active_support/dependencies.rb:251:in `block in require'
/home/four04/.rvm/gems/ruby-1.9.3-p362/gems/activesupport-3.2.9/lib/active_support/dependencies.rb:236:in `load_dependency'
/home/four04/.rvm/gems/ruby-1.9.3-p362/gems/activesupport-3.2.9/lib/active_support/dependencies.rb:251:in `require'
/home/four04/.rvm/gems/ruby-1.9.3-p362/gems/activerecord-3.2.9/lib/active_record/migration.rb:537:in `load_migration'
/home/four04/.rvm/gems/ruby-1.9.3-p362/gems/activerecord-3.2.9/lib/active_record/migration.rb:533:in `migration'
/home/four04/.rvm/gems/ruby-1.9.3-p362/gems/activerecord-3.2.9/lib/active_record/migration.rb:528:in `migrate'
/home/four04/.rvm/gems/ruby-1.9.3-p362/gems/activerecord-3.2.9/lib/active_record/migration.rb:720:in `block (2 levels) in migrate'
/home/four04/.rvm/gems/ruby-1.9.3-p362/gems/activerecord-3.2.9/lib/active_record/migration.rb:775:in `call'
/home/four04/.rvm/gems/ruby-1.9.3-p362/gems/activerecord-3.2.9/lib/active_record/migration.rb:775:in `block in ddl_transaction'
/home/four04/.rvm/gems/ruby-1.9.3-p362/gems/activerecord-3.2.9/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
/home/four04/.rvm/gems/ruby-1.9.3-p362/gems/activerecord-3.2.9/lib/active_record/transactions.rb:208:in `transaction'
/home/four04/.rvm/gems/ruby-1.9.3-p362/gems/activerecord-3.2.9/lib/active_record/migration.rb:775:in `ddl_transaction'
/home/four04/.rvm/gems/ruby-1.9.3-p362/gems/activerecord-3.2.9/lib/active_record/migration.rb:719:in `block in migrate'
/home/four04/.rvm/gems/ruby-1.9.3-p362/gems/activerecord-3.2.9/lib/active_record/migration.rb:700:in `each'
/home/four04/.rvm/gems/ruby-1.9.3-p362/gems/activerecord-3.2.9/lib/active_record/migration.rb:700:in `migrate'
/home/four04/.rvm/gems/ruby-1.9.3-p362/gems/activerecord-3.2.9/lib/active_record/migration.rb:570:in `up'
/home/four04/.rvm/gems/ruby-1.9.3-p362/gems/activerecord-3.2.9/lib/active_record/migration.rb:551:in `migrate'
/home/four04/.rvm/gems/ruby-1.9.3-p362/gems/activerecord-3.2.9/lib/active_record/railties/databases.rake:179:in `block (2 levels) in <top (required)>'
/home/four04/.rvm/gems/ruby-1.9.3-p362/bin/ruby_noexec_wrapper:14:in `eval'
/home/four04/.rvm/gems/ruby-1.9.3-p362/bin/ruby_noexec_wrapper:14:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
</pre>

**Comment by rye** [comment]
This is actually because the original migrations to create the tables were removed. I think this was @samercier or @computerguy505. Whatever the case, I'm removing the migration files which drop those tables, and people will need to migrate.

**Comment by cg505** [comment]
Yeah, this is my fault. However, the better solution would be to readd the migration that creates the tables. Will do

**Comment by cg505** [comment]
Yeah, should be better now.
