### ISSUE TITLE
Finish/fix background changes

### ISSUE THREAD

**Issue by samontea** [frc461/website-2013#39]
This has two main sub-issues.
1. Getting smooth scrolling to become an integral part of our website
2. Disabling the background moving in tablet and phone modes.

EDITED BY @four04: Also make it not break when in tablet and phone mode.

**Comment by cg505** [comment]
Is this done? And does it at least kind of work on ie?

**Comment by braddoeswebdev** [comment]
It at least kind of works, if I remember correctly.

**Comment by cg505** [comment]
Yes it does.
