### ISSUE TITLE
File uploader

### ISSUE THREAD

**Issue by samontea** [frc461/website-2013#41]
OI wants this now!

**Comment by cg505** [comment]
What is this?
If they just want to upload pictures, they can make an album, and then there is a "Add Photos" link.

**Comment by braddoeswebdev** [comment]
But they want to upload something that's not a picture.

**Comment by cg505** [comment]
Ah.

Can paperclip handle this?

**Comment by cg505** [comment]
And may I also ask why?

**Comment by braddoeswebdev** [comment]
Paperclip just does pictures.

I'm not sure exactly.  PDFs of award submissions and that kind of thing, I'd imagine.

**Comment by cg505** [comment]
Ah. We can still probably find a gem somewhere for something.

**Comment by cg505** [comment]
Try http://www.tutorialspoint.com/ruby-on-rails/rails-file-uploading.htm or https://github.com/ksylvest/attached?

**Comment by rye** [comment]
We need to facilitate uploading to (URL REDACTED) (though it's not necessary at this point because we have the web uploader, we need to be able to do it at some point)

**Comment by cg505** [comment]
Working on a hacky thing that should not be public knowledge to do that.

**Comment by rye** [comment]
Mmkay.

**Comment by cg505** [comment]
Done.
