### ISSUE TITLE
Be more efficient with the screen.

### ISSUE THREAD

**Issue by rye** [frc461/website-2013#42]
This means eliminating some space, and using more of the screen on each page.

**Comment by cg505** [comment]
This has been consistently one of our goals, and I think at this point we aren't really lacking in this area.

Any specific ideas?

**Comment by rye** [comment]
We aren't as bad as we could be, but having a panel which extends across the entire screen and is only halfway filled is somewhat inefficient (I'm speaking about the "recent posts" renderer in the main page.)

I'm thinking we could also benefit from putting things which are global and are reused often into partials, and rendering them. I don't think that the actual _twitter_feed.html.erb is ever used anywhere any more, so you could probably remove that and move _sidebar_twitter_feed.html.erb to _twitter_feed.html.erb.

I'm also thinking that the search bar could probably stand to be moved to the navbar, top-right corner.
