### ISSUE TITLE
Resizing search bar only works in Firefox.

### ISSUE THREAD

**Issue by cg505** [frc461/website-2013#47]
I was so happy to get that working... :(

We may need to do the set sizes thing, but preferably only on webkit-based browsers (and maybe IE)

**Comment by cg505** [comment]
Oops.

**Comment by cg505** [comment]
@four04, are you working on this?

**Comment by rye** [comment]
Somewhat.

**Comment by cg505** [comment]
Okay, I'm going to revert to the system pre- b9063bc74ad1fe0689eeca1cdaa65739a97335a9. That is, have a set width, and have tablet view have a different set width.

**Comment by rye** [comment]
Perhaps, as a "give-up-and-do-something-different" approach, we could move the search bar to the navbar at the top or something like that, not in it's own part of the sidebar. Or, try taking it out of the div, and putting it at the top of the sidebar? Not sure.

**Comment by cg505** [comment]
This has been fixed for a while.
