### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by cg505** [frc461/website-2013#48]
Especially in navigation on the navbar, how do we sort that stuff so it goes the way we want?

**Comment by cg505** [comment]
I propose a 'sort index' column for pages.

**Comment by braddoeswebdev** [comment]
That's doable.  We could just sort by title, but that would give us more control.

**Comment by cg505** [comment]
Done, see commit 24bcc066c2c71ec9be444f2c9d025ae47210bb59.
