### ISSUE TITLE
Close security holes required to make mass photo uploading work

### ISSUE THREAD

**Issue by braddoeswebdev** [frc461/website-2013#49]
Change the photos controller & ability model to make things properly secure after we import all the pictures.

**Comment by cg505** [comment]
What specific security flaws were opened?

**Comment by braddoeswebdev** [comment]
The controller is no longer checking for the authenticity token thing & the permissions were set so that anybody can upload pictures.  Also, those changes are just on the deploy branch.

**Comment by cg505** [comment]
I believe those problems are with documents.

**Comment by braddoeswebdev** [comment]
That too, actually.

**Comment by samontea** [comment]
Hey have you imported the pictures yet?

**Comment by braddoeswebdev** [comment]
Yeah - plus we can use the actual photo uploader thing to do that now.  I'll take care of that on Monday.

**Comment by cg505** [comment]
Is it done?

**Comment by braddoeswebdev** [comment]
Mmm... yeah... I'll fix that tomorrow :wink:

**Comment by braddoeswebdev** [comment]
Done!
