### ISSUE TITLE
Photo thumbnails

### ISSUE THREAD

**Issue by cg505** [frc461/website-2013#51]
This is important, as sending 50 HD pictures to the client is SLOW

**Comment by rye** [comment]
Could be done with RMagick.

**Comment by braddoeswebdev** [comment]
Paperclip will use RMagick if we tell it to.  The question then becomes how well will it work on Heroku.

**Comment by braddoeswebdev** [comment]
I do still need to go back & re-upload the pictures that were there.

**Comment by cg505** [comment]
Nope, there's a rake task for that.

**Comment by braddoeswebdev** [comment]
Tried that.  It didn't get along with the whole FTP thing.

**Comment by cg505** [comment]
:(

**Comment by braddoeswebdev** [comment]
I know, right?

**Comment by cg505** [comment]
But before you do, are those really the dimensions we want?
