### ISSUE TITLE
Remove all 461-specific references, specifically to assets.boilerinvasion.org, also to everything else.

### ISSUE THREAD

**Issue by rye** [frc461/website-2013#53]
Make URLs and filenames defined in secret.rb;

Make it easier for someone reading our code to know what to define in secret.rb, as well.

**Comment by cg505** [comment]
I don't see the problem with specific references.

**Comment by braddoeswebdev** [comment]
It's not really necessary since I don't imagine too many people will be actually using this code but us, but it's not a terrible idea.  It's one of those "best practices" type things.

**Comment by rye** [comment]
I think perhaps I will make it such that everything is defined in the application controller, which is more easily changed than secret.rb

**Comment by rye** [comment]
I guess we can keep it.
