### ISSUE TITLE
Search bar results are confusing

### ISSUE THREAD

**Issue by cg505** [frc461/website-2013#54]
Headers are styled the same as results, causing confusion. Also, everything seems a little to big to me.

**Comment by braddoeswebdev** [comment]
IIRC, the headers are slightly different, but more differentiation wouldn't be a bad idea.  Everything is kind of big - but I don't really see anything wrong with that.

**Comment by cg505** [comment]
This is mostly fixed, but would benefit from more work still.

**Comment by rye** [comment]
We've changed the h-tags, if that's what you meant. We could probably change the font color but I think the scaling is pretty good.

**Comment by cg505** [comment]
Meh, it's fine.
