### ISSUE TITLE
Give more credit to sponsors

### ISSUE THREAD

**Issue by cg505** [frc461/website-2013#56]
Important!

**Comment by braddoeswebdev** [comment]
Yep.  We probably need a top-level sponsors page, and maybe some logos of major sponsors on the bottom of the page above or below the social media icons.

**Comment by rye** [comment]
We have a sponsors page now, but we need information about our sponsors on it.

**Comment by rye** [comment]
So the sponsors page needs content.

Considering that this is a content-related issue, not actually a framework-based issue, it is closeable.

**Comment by cg505** [comment]
I dissagree. We should add a WL, Cat, and Purdue logo to the layouts/application.html.erb. Agree or dissagree?

**Comment by rye** [comment]
In the sidebar somewhere. Go ahead.

**Comment by cg505** [comment]
Done, see a64e9571497d53e6c26f1df1dcb8e031e4f17847.
