### ISSUE TITLE
Adminify yourself! 

### ISSUE THREAD

**Issue by cg505** [frc461/website-2013#58]
Can't someone, in their post from a user edit form, indicate admin? Won't that go through?

**Comment by cg505** [comment]
If a custom post command is crafted, one can post with admin => true to /users to create a user with admin rights.

**Comment by braddoeswebdev** [comment]
Yeah, someone should add some logic to the controller to stop that from happening :wink:

**Comment by cg505** [comment]
Working on it, not an easy thing to do (since you can't access session variables).

Likewise, you can manually add yourself to groups that aren't joinable.

**Comment by cg505** [comment]
Oops.

**Comment by braddoeswebdev** [comment]
What do you mean you can't access session variables?  You can use current_user in controllers too.

**Comment by cg505** [comment]
Oh, yeah. I was trying to do it from the model, but I've got it figured out now.

**Comment by cg505** [comment]
Fixed in e5de4111e79de47d73bbea56ddaf9fe04b97ab8c.
