### ISSUE TITLE
Removing page IDs from auto-generated URLS isn't finished yet

### ISSUE THREAD

**Issue by rye** [frc461/website-2013#62]
If I edit the frontpage, for example, it redirects to /pages//(\d+)//edit, not /pages/frontpage/edit, like I think it should

**Comment by cg505** [comment]
That is intentional. The fancy url-handling code is not yet set up to work with edits.

**Comment by cg505** [comment]
It's much more hassle than it's worth.

**Comment by cg505** [comment]
You'll also note that once you finish the edit, it sends you to /pages/(\d+).
