### ISSUE TITLE
Fix iCal

### ISSUE THREAD

**Issue by rye** [frc461/website-2013#63]
Google Calendar doesn't like our generated iCal thing, for some reason.

`Settings Error: We could not parse the calendar at the url requested.`

**Comment by rye** [comment]
Note, `working on it` tag is being removed.

**Comment by cg505** [comment]
Does anyone have any clue why this is happening? As far as I can tell, the output is completely valid.

**Comment by rye** [comment]
Has any progress been made? Are we sure that the MIME-type is correct?

**Comment by cg505** [comment]
I believe at one point I figured out that the problem was that in the
output DTSTART and DTEND were being formatted wrong, but I don't know in
what way. Look for an iCal verifier online.

**Comment by rye** [comment]
Hmm. Upon [plugging it in](http://severinghaus.org/projects/icv/?url=http%3A%2F%2Fboilerinvasion.org%2Fevents.ics) to a validator, this is, indeed, correct.

**Comment by rye** [comment]
According to some [third-party documentation](http://www.kanzaki.com/docs/ical/dateTime.html), we need to do some prefixing or something.

**Comment by rye** [comment]
Also, DTSTART and DTEND are both incorrect. To my understanding, both must be prepended with the date. I'll work on this issue.

**Comment by rye** [comment]
The reason this is problematic is that [icalendar's date_time system](https://github.com/icalendar/icalendar/blob/master/lib/icalendar/values/date_time.rb) seems to be incompatible with ActiveRecord's. It appears that you can pass it a pre-formatted string, however (I am testing this currently).

**Comment by rye** [comment]
According to the iCalendar validator I linked previously, this works correctly. @btgeek, I'd like to get this deployed ASAP so that I can test it on the actual website's iCalendar feed.

**Comment by braddoeswebdev** [comment]
It has been pushed - give it a try.

**Comment by rye** [comment]
It works! Validator reports nominal syntax, Google Calendar works.

**Comment by rye** [comment]
:D

**Comment by rye** [comment]
Oh, time zone is not accounted for. I'll fix that.

**Comment by rye** [comment]
Okay, master is now deploy-ready again.

**Comment by braddoeswebdev** [comment]
I did the thing.

**Comment by rye** [comment]
Time zone should be working, however I think Google is caching it and that's messing it up. I'll look into it later on.

**Comment by cg505** [comment]
I think it's working for me.

**Comment by rye** [comment]
Yes, it's working for me as well. The previous events have since repopulated.
