### ISSUE TITLE
Resolve branches

### ISSUE THREAD

**Issue by Sammidysam** [frc461/website-2013#65]
We need to probably delete old branches that are either done or are not going to be finished and merged.  Are there any branches that are still being worked on?

**Comment by Sammidysam** [comment]
Also, do we want to use branches for new items from now on?

**Comment by rye** [comment]
Of course.

EDIT: Whether or not we actually will remains to be seen.

**Comment by Sammidysam** [comment]
I will, then.  I would prefer our current branch system is cleaned up first, though.

**Comment by Sammidysam** [comment]
Wait, were you commenting on the question in my issue or comment to my issue?

**Comment by rye** [comment]
Your comment. Since we haven't committed much if at all in the past few months, I would say it is safe to say that nothing is currently being worked on.

**Comment by Sammidysam** [comment]
Okay.  Here is what I think we should do to various branches

###### To be deleted
- fontchange
- retabify
- staging
- third-level-dropdowns
- twitter-fixes

###### To be merged now and then deleted
- fixes
  
  This will need to be tested, though, and maybe there aren't actually any fixes within.  If so, we would just delete the branch.

###### To be kept as a separate branch
- rails-4

**Comment by Sammidysam** [comment]
Any approval, denial, or comments relating to what I suggest should be done to the branches?

Should the two commits in `fixes` be merged to master?

**Comment by rye** [comment]
Probably, if they're stable.

**Comment by cg505** [comment]
I agree with everything.

**Comment by Sammidysam** [comment]
`fixes` has been merged.  I will delete all of the branches besides `clean-up` and `rails-4` (of course, master will be kept as well).

**Comment by Sammidysam** [comment]
Done.
