### ISSUE TITLE
Dropdowns don't work on /events ...?

### ISSUE THREAD

**Issue by cg505** [frc461/website-2013#69]
This is something I noticed that is really weird while browsing the site on chrome.

**Comment by Sammidysam** [comment]
Happens on Firefox as well.  I noticed this earlier I think, but forgot to report it.

**Comment by Sammidysam** [comment]
I think it works on the `rails-4` branch, so maybe updating gems fixes this.

**Comment by cg505** [comment]
That might be related to turbolinks. Do we use that on the `rails-4` branch?

**Comment by Sammidysam** [comment]
This is now fixed on the deployed version on Firefox 27.0.1.  I have no idea why.  Is it the same on Chrome?

**Comment by Sammidysam** [comment]
The deployed version works on Firefox, Chrome, and Internet Explorer.  That yields a close.
