### ISSUE TITLE
Indicate "today" on the calendar better

### ISSUE THREAD

**Issue by Sammidysam** [frc461/website-2013#70]
This was taken on January 19.  I think that we should make it more clear what day is today.

http://s11.postimg.org/ewq26hvf7/today.png

**Comment by rye** [comment]
I would say the best way to go about indicating this is to both increase the RGB values of the background color of the active day, and then, if necessary, make it more transparent.

**Comment by Sammidysam** [comment]
Maybe a neat border, too.

**Comment by rye** [comment]
Unfortunately, someone decided to use a gem because of laziness. We can probably just override, but that feels dirty to me. Whatever.

**Comment by Sammidysam** [comment]
Thoughts on the current work, everyone?
