### ISSUE TITLE
Faster?

### ISSUE THREAD

**Issue by rye** [frc461/website-2013#72]
While the website certainly is faster than its PHP-based predecessor, I've noticed that things are a little sluggish with it. Namely, this effect applies to generic queries and connections. I have my doubts that this is Rails' fault, and as such it is mostly our own fault.

One possible fix would be to use (if we're not using it already) [Unicorn](http://rubygems.org/gems/unicorn). Stuff could get served much faster, if it was set up properly.

Another possible fix would be to go through our codebase and try to both modularize and clean up unnecessary things that are taking the most time-per-request. [This StackOverflow post](http://stackoverflow.com/questions/6324335/rails-how-to-optimize-my-website#6346813) explains things rather nicely.

**Comment by rye** [comment]
Selective and/or fragment and/or any kind of caching would be good to implement.

**Comment by rye** [comment]
If all of these improvements have been made or would not work, it would be good to just optimize everything. I've read that Rails uses caching in production, is this in effect for the deploy of our website?

**Comment by cg505** [comment]
I believe so.

**Comment by cg505** [comment]
We need to stop querying twitter on every request.

**Comment by rye** [comment]
So we should keep a cache? Would we just refresh it on a minutely basis?

**Comment by cg505** [comment]
I was thinking something like that.

**Comment by rye** [comment]
Okay. I can work on this.

**Comment by rye** [comment]
How should we do this rails-side?

**Comment by cg505** [comment]
A model with a minutely updated cache of tweets. Use some sort of
scheduling gem. Plenty exist.

Also, http://railscasts.com/episodes/368-miniprofiler.

**Comment by rye** [comment]
Closing this issue since we're going to rewrite soon (I hear this, at least).

**Comment by cg505** [comment]
Yes.
