### ISSUE TITLE
Twitter images not rendering properly when HTTP to "pbs.twimg.com" is blocked.

### ISSUE THREAD

**Issue by rye** [frc461/website-2013#75]
This is what they look like when they aren't loaded properly:

![image](https://f.cloud.github.com/assets/1566689/2164297/34d630ec-94ea-11e3-9912-2fdf312867f9.png)

This could be bypassed by switching from using HTTPS connection to `pbs.twimg.com` as opposed to HTTP. HTTP connections are restricted by our school's filters as `forums.social_networking` whereas HTTPS connections are unblockable with the current system (thanks, LightSpeed! :cookie:). If there's an option when generating the image tag (i.e. getting the URL), we should go for the HTTPS alternative if that is available.

**Comment by Sammidysam** [comment]
We could also try to detect if it fails to load, and then if it fails not show the image altogether.

**Comment by rye** [comment]
Okay. I'll pick up this one and make it use HTTPS if possible. We may add the failure checking later--JavaScript should be able to handle that. For now, I'll fix this issue.

**Comment by swapnil-kotwal-sp** [comment]
twitter still not rendering images for me ? It only shows error message " GET https://pbs.twimg.com/profile_images/3033271751/50eb4531b7718778d5d2e47b30a179b6_normal.jpeg net::ERR_NAME_NOT_RESOLVED"

**Comment by rye** [comment]
Is this behind the school's firewall? It could be being blocked.  Works for me behind my school's, but they don't block Twitter over HTTPS.

**Comment by rye** [comment]
@Sammidysam, I like your idea about the failed-to-load detection.  Using callbacks like [this](http://stackoverflow.com/a/9815854) would be a fairly trivial means of detecting if things load properly or not.  If they fail, we can just add a class to the image (perhaps with an animation that linearly decreases the element height to zero and then sets `display` to `none`.

**Comment by Sammidysam** [comment]
That looks nice.  I would probably instead just have the image not show up altogether to show no signs of failure.  It might be good to show a sign, though.

**Comment by rye** [comment]
Yes, perhaps a small amount of text like `[photo]` would be good.  Something to consider.

**Comment by Sammidysam** [comment]
I agree some text would be good.  Maybe we can show it if somebody is logged in and an admin, and hide our failure otherwise?

**Comment by rye** [comment]
That sounds like a fairly good design idea. Admins can be aware of these things (but we should still at least handle errors), and users probably should not be. It appears that the Twitter feed generator already inserts a link to the image, so we can just use JavaScript to hide the image if it fails to load.  I'm going to write a more general issue to this effect.
