### ISSUE TITLE
Smaller highlight on Twitter images?

### ISSUE THREAD

**Issue by rye** [frc461/website-2013#76]
Currently it appears that Twitter images are rendered with a 50-50 balance between the gold color and the background (the little corner highlights expand over 50% of the image).

I would suggest that we make those slightly smaller. Perhaps 1/3 of the width and height as opposed to 1/2?

**Comment by rye** [comment]
This is using 1/4 of the image, and I think it looks a bit nicer.

![mmm](https://f.cloud.github.com/assets/1566689/2164455/fb1d08ec-94eb-11e3-9360-302b7c2c4d09.png)

**Comment by Sammidysam** [comment]
I agree.

**Comment by cg505** [comment]
I'm changing it down to 33% for now.

**Comment by Sammidysam** [comment]
That works.
