### ISSUE TITLE
Critical Updates (this is ridiculous)

### ISSUE THREAD

**Issue by rye** [frc461/website-2013#78]
In addition to being good practice, it is incredibly important that we ensure that **all** plugins, gems, and external projects that we consume are fully up-to-date.

![[screenshot]](https://cloud.githubusercontent.com/assets/1566689/2685908/a1024464-c1da-11e3-955a-a660c6f51293.png)

It appears that we have failed to do that, judging by the various complaints that loading the page throws. These errors have been appearing for too long and it is time that action be taken. It appears that the Facebook API has changed since we included the plugin, and it appears that the plugin is being loaded incorrectly. It also appears that a jQuery module is not using proper JavaScript (big surprise there! :clap:), an issue that needs to be rectified. I will run updates on the `updates` branch (merging `master` in if it already exists, of course) and fix all of the content loading errors, then merge back to `master` after that process is complete. If possible, all jQuery modules will be updated to the latest version, hopefully versions which use correct JavaScript.

In addition, I've stated before but I now have motivation to rewrite the fancy jQuery modules that we have included. It appears that we cannot handle maintaining said modules and it appears that we need to put in extra effort to make them remain happy. A long-term plan of mine is to clean up the JavaScript code that we have in our codebase; having over 4 `<script>` tags is ugly. We need to have on-load calls _put into an on-load callback_, not loaded once the DOM tree is built. In addition, all of the JavaScript needs to be modularized and made more pretty. As it stands, many audits give us critical problems or warnings that suggest that we need to pay attention to how the website is built. I will put work regarding this into a branch entitled `refactor`, considering that the activity I will be partaking in is, indeed, refactoring the code so that it is more sane.

I will gladly accept others' contributions on the aforementioned branches, however since I am the sole person who seems to believe that outdated modules and poorly-organized code constitute a "bad thing," it seems that I will be alone. Thus, I will assign myself.

**Comment by rye** [comment]
In regards to the JavaScripts, further auditing is showing a ridiculous amount of CPU time that is wasted by the jQuery modules. Each page load **_should not**_ take more than one second, however a full page load (running locally and measured to completion of all of the trailing `<script>` tags' code, mind you) currently takes over 5 seconds, which is absolutely derisible.

**Comment by rye** [comment]
@btgeek, it seems that your deployment script may need to be refactored as well. If this becomes a problem, I suppose I'll give up on updates and just jump to refactoring our existing code (and updating the Facebook plugin).

**Comment by braddoeswebdev** [comment]
Several points here:
- The melodramatic bit is getting old, dude.
- I wasn't aware of the Facebook thing being out of date.  Good catch.  So update the thing, make sure it works, and push it so I can push it.
- There are no errors on Firefox, other than Facebook whining.  Will updating jQuery make your errors go away?  Possibly.  Will it make others show up for someone?  Probably.  And that's just talking about us, not some alumnus's grandma who keeps tabs on the team that's still using IE6.  Welcome to web development.
- If you want to try and out-do all the people who have spent days... months... maybe years working on & optimizing these other libraries we're using, go right ahead - which still requires keeping up with updates, except now you need to know the implementation details too.  Just put it a branch and don't break anything.
- Refactoring is a wonderful idea.  Just remember that many of the auditing tools I've seen focus a lot on "last mile" optimizations that might shave a few CPU cycles off your load time - so prioritize accordingly.
- How do you propose refactoring deployment?  Automatically updating things before pushing is a thing... but that may create issues & break stuff.

**Comment by rye** [comment]
In regards to Chrome's whining, it could very well just be Chrome with a newer/older JavaScript spec in use. Rather than rewriting a lot of the crap, I'll just forget about it. Rails makes this painful to do, because running major updates (like changing to Rails 4.1.0) requires removing code that would be autogenerated. I will definitely be moving the JavaScript around into a JavaScript file and making it more modular.

Deployment is hard to understand because I don't have the script sitting in front of me (so I can't tell exactly what would need to be changed). To my understanding, previous attempts to update have failed because the deployment script did not work. It would be great if we didn't need to have absolute versions defined and we could just run "bundle update" to update everything. That's what I initially tried to do but very little further progress was made (e.g. moving from Rails 3.2.16 to 4.1.0) because of pre-existing code that was 3.2-specific. To update Rails, it seems that the only somewhat-sane way to go about doing that is to make a completely new app, unless a lot of editing is suitable.

I'll close this issue and make a new one for the refactoring. The updates are currently being finalized and I will merge back to master with our pre-existing Gemfile and not work on updating the core. I'll work on updating the Facebook plugin on the `updates` branch as well. (`refactoring` will be used for refactoring).

Just a little side note, melodrama is my method of getting people to read stuff. [[EDIT: It seems that it worked :smile:]]

**Comment by braddoeswebdev** [comment]
Precisely.  And staying on older Rails isn't the end of the world.  Rails 3 is still supported, and I think we generally keep up on the updates.  Rails 4 didn't break much, so it shouldn't be too painful to upgrade - but it's not a particularly high priority.

Deployment is just merging to a branch and pushing to Heroku (unless we have to rebuild the CSS/JS, in which case some other stuff happens to build & copy those to the asset host first).  

I read the first little bit and then ignored the rest. My better judgment took over a few hours later and I finished reading & replied to make an effort to keep you from doing anything stupid and/or causing drama.  Simply stating your case makes me want to treat you like a reasonable human being.  I'm not inclined to take you or your concerns seriously when you go on and on like that.

**Comment by Sammidysam** [comment]
Is all of the work on `updates` done (i.e. can the branch now be deleted)?  If so, delete the branch.  No point in leaving it open if all is done, unless we want to leave it open as a place to conduct updates to the various services that we use.
