### ISSUE TITLE
Refactor Code

### ISSUE THREAD

**Issue by rye** [frc461/website-2013#79]
Previously discussed in #78, our codebase (especially the JavaScript) should be seriously refactored. It is somewhat ridiculous to have more than 4 or so trailing `<script>` tags at the end of the document, and so I'd like to move whatever onload stuff into a JavaScript file. As such, I will be working on this on the `refactoring` branch.

**Comment by Sammidysam** [comment]
Why not `clean-up`?

**Comment by rye** [comment]
Because it's not technically clean-up.

**Comment by Sammidysam** [comment]
Isn't it a subset?

**Comment by rye** [comment]
I suppose in a way.

**Comment by Sammidysam** [comment]
Then it is clean up.  I have done refactoring work in `clean-up` before, so I don't see a reason why it needs its own branch now.

**Comment by rye** [comment]
I have now deleted the `refactoring` branch and will continue to do work on `clean-up`.

**Comment by Sammidysam** [comment]
You merged the current `refactoring` work into `clean-up`, right?

**Comment by Sammidysam** [comment]
Never mind that.

**Comment by Sammidysam** [comment]
Thanks!

**Comment by rye** [comment]
Not a problem.

**Comment by Sammidysam** [comment]
In fact, now that I think about it, having this issue separate from the issue about cleaning up the code seems a bit pointless to me.

**Comment by rye** [comment]
Yeah, I think I may close it shortly.
