### ISSUE TITLE
Variable Name Changes

### ISSUE THREAD

**Issue by rye** [frc461/website-2013#82]
### Subtopic 0: Shorthand

Variable names like `grp` cause ambiguity and problems. With auto-completion or some semblance of a work ethic, there is no reason to use such shortcuts as that. It's distracting and unnecessary.
### Subtopic 1: Mismatched CamelCase/Hyphenated/Underscored Variable and Function Names

As this project was initially written by multiple individuals with different experience and coding standards, multiple different variable naming schemes have been used throughout the codebase. We need to select either CamelCase or underscored variable and function names. Variable and function names need to be as descriptive as necessary. I'd be fine with using either one if that's what we decide. Consistency is key, though.

**Comment by rye** [comment]
I'll be working on beefing up the names of variables and functions, but we should determine whether or not we're using CamelCase or underscores.

**Comment by Sammidysam** [comment]
As it is Ruby, I would say variable and function names should be underscored.  Class and module names should be CamelCase, however.

 I agree with `grp` being dumb, and `group` being a better name.

**Comment by rye** [comment]
I agree with the class and module naming convention. I will also de-shorten variable names like that. 

This work will be performed on the `clean-up` branch.

**Comment by Sammidysam** [comment]
There is no need to do this anymore since we are making a new website.
