### ISSUE TITLE
Updates, Inertia

### ISSUE THREAD

**Issue by rye** [frc461/website-2013#85]
This is kinda a meta-y sort of thing, but quite applicable to where things are going right now.

I understand that this project has been seen as "done" for quite some time now (a year-ish, judging roughly from the contribution graphs), but there's an enormous amount of cleanup and refactoring and updating that we can do.  If we do that and keep things rolling, I'd say that this repository would be highly suitable for keeping the current website in.  Below is a rough list of things that can and probably should be done to make the website more current.  Critique is encouraged.
- **Update Ruby/Rails dependencies, get rid of deprecated references and use newer, more shiny references.**  For this one, I'm looking directly at the authentication system.  Almost directly after we finished this, Rails 3.<something, I'm too lazy to look up the minor version> came out, with a shiny `has_secure_password` thing. We should use that.  In addition, _and more importantly_, Ruby 2.1 addresses a wide range of vulnerabilities (and Ruby 1.8/1.9 are both very-much-so slower than the latest ones).  It's very good practice to keep track of these things.
- **Update Gem dependencies, and get rid of obsolete code.**  If we don't need something, we can get rid of it.  If there's something that can be expanded out into its own little module, then we can do that also.
- **Use JavaScript more for DOM stuff.**  I think we were pretty much all infatuated with ERB and how beautiful it was (and still is), but JavaScript has the ability to interact with the DOM, and quite easily.  [Prototype.JS](http://prototypejs.org/), a framework I'm using for a commercial project right now, is an excellently-written framework that makes JavaScript much less painful (It's effectively jQuery but much, much cleaner, and much more sensical).  It enables writing object-oriented JavaScript code in a way that is more Ruby-like, and would make our lives a bunch easier.  In addition, it also has support for AJAX requests (and it does it all in a way that makes me really happy), and so we might consider doing things like making content refresh on-screen.
- **Consider a more [SPA](http://en.wikipedia.org/wiki/Single-page_application)-like approach.**  We might consider doing things in a more single-page manner.  Something to think about.  It'd make things a lot faster and also offline-friendly, if we wanted that (we could even write cache manifests :+1:)

---

I suppose the big thing to say is, let's bring this thing back to life.  Let's revitalize and restore it, make it modern, fast, and shiny, and make it do its purpose and do it well.

And of course, since I'm not officially on the team any more, I want others' approval before I start waving my hands and making magic happen.  If anyone here voices their agreement with one or more of the aforementioned points, and there seems to be consensus, I'll gladly take this up and start forging ahead.

> Porro et sursum!
> &mdash; Me.

**Comment by braddoeswebdev** [comment]
Yeah, we're starting a brand new codebase here in the relatively near future, to address those concerns and many other ones.  That's what you get for not showing up to meetings - you miss out on discussions like that :wink: 

You kids and your single page apps... back in my day we had to completely re-render the whole page every time we wanted to do anything!  That being said we're all a lot more on the JS train than when we put this thing together...

**Comment by rye** [comment]
In addendum:

It might also be worth our time to start phasing out Bootstrap.  I've spoken with a few web designers who think of Bootstrap as the devils' spawn.  Of course, we have done so much with it that it'd be better to simply distill it down into our own grid system (which is actually easier than it sounds, I'm doing it right now as a matter of fact).

One possibility is to use [flexboxes](http://css-tricks.com/snippets/css/a-guide-to-flexbox/), which are [fairly well-supported](http://caniuse.com/#feat=flexbox).

**Comment by rye** [comment]
Ah, okay, so that (the whole rewrite thing) makes a lot more sense.  I assume that's what the super-secret new repository is for?

**Comment by rye** [comment]
As a side note (not a complaint or anything like that, the status quo is totally understandable), I'd totally love to hear news and discussion about that kind of stuff, even if it is in passing and very scant.

**Comment by braddoeswebdev** [comment]
That's just some sketches & ideas at the moment.  We're not entirely decided on all the details of what we're doing yet.

Then you should show up to meetings :grinning: Once we get more concrete plans in place & start moving we'll probably be documenting things a little more.

**Comment by rye** [comment]
@btgeek Can I get travel reimbursements? :wink: #hshackersreference

**Comment by braddoeswebdev** [comment]
Ha!

No.

**Comment by rye** [comment]
Yeah, thought so. Hangouts are great; I'll poke @samontea or @cg505 and make them answer video calls at robotics meetings.

**Comment by rye** [comment]
If not just to listen.
